# Lab 1 - Original

### Lena Press Arai

In [772]:
import pandas as pd
import numpy as np
import pdb
import scipy.stats
import requests
import csv
import io
import json
import sklearn
import json
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.svm import SVR
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
import statsmodels.nonparametric.api as nparam
import matplotlib.pyplot as plt
%matplotlib inline

## Import Data

In [601]:
data_url = "https://drive.google.com/uc?export=download&id=1-NRy3Q2AewrnZcenGmf1x48vvj2bxqeb"

# Function Definitions
def get_csv(csv_url):
	"""
		get_csv

		Attempt 10 times to fetch the csv file before terminating program.

		Return raw csv data on success
	"""
	attempts = 1
	data = None
	while data is None and attempts <= 10:
		print(">> Fetching CSV file (Attempt #" + str(attempts) + ") ...")
		r = requests.get(csv_url)
		status_code = r.status_code

		if status_code >= 200 and status_code < 300:
			data = r.text

		attempts += 1
	
	if data is None:
		print(">> Could not download csv file.")
		exit(1)

	print(">> CSV retreived.")
	return data


def csv_to_json(csv_data):
    """
        csv_to_json

        Takes in csv_data and converts it to a file object. The file object
        is then converted to a csv reader to iterate elegantly over rows.

        Rows are converted to JSON objects.

        Returns JSON formatted csv data
    """
    print(">> Converting CSV to JSON ...")
    json_data = []

    fin = io.StringIO(csv_data)
    reader = csv.reader(fin)

    # Extract headers first
    headers = reader.__next__()

    # Convert each row to JSON
    for row in reader:
        row_obj = {}
        for index, value in enumerate(headers):
            row_obj[value] = row[index]

        json_data.append(row_obj)

    # Pretty Print and return the JSON
    return json.dumps(json_data, indent=2)


# Execution starts here
csv_data = get_csv(data_url)
json_data = csv_to_json(csv_data)

print(">> Writing data to './output.json' ...")
with open("./output.json", "w") as fout:
	fout.write(json_data)

>> Fetching CSV file (Attempt #1) ...


ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1-NRy3Q2AewrnZcenGmf1x48vvj2bxqeb (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x114c9e2b0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

## Above code is stupid. This works:

## Training Data

In [644]:
training_data = pd.read_csv("https://drive.google.com/uc?export=download&id=1-NRy3Q2AewrnZcenGmf1x48vvj2bxqeb")
#training_data

In [603]:
training_data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

## Application Data

In [697]:
test_data = pd.read_json("https://drive.google.com/uc?export=download&id=1OevU8V0tyhF9Sfxs_DzPqz1jBdg4FZBE")
#test_data

## Separating Training & Test Sets

In [646]:
y_all = training_data['Chance of Admit ']
x_all = training_data[['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA', 'Research']]


y_train, y_test = train_test_split(y_all, test_size=0.2, random_state=0)

x_train, x_test = train_test_split(x_all, test_size=0.2, random_state=0)

## Separating Training IVs

In [660]:
Serial_No_train = pd.DataFrame(x_train['Serial No.'])

GRE_Score_train = pd.DataFrame(x_train['GRE Score'])

TOEFL_Score_train = pd.DataFrame(x_train['TOEFL Score'])

University_Rating_train = pd.DataFrame(x_train['University Rating'])

SOP_train = pd.DataFrame(x_train['SOP'])

LOR_train = pd.DataFrame(x_train['LOR '])

CGPA_train = pd.DataFrame(x_train['CGPA'])

Research_train = pd.DataFrame(x_train['Research'])

## Separating Test IVs

In [661]:
Serial_No_test = pd.DataFrame(x_test['Serial No.'])

GRE_Score_test = pd.DataFrame(x_test['GRE Score'])

TOEFL_Score_test = pd.DataFrame(x_test['TOEFL Score'])

University_Rating_test = pd.DataFrame(x_test['University Rating'])

SOP_test = pd.DataFrame(x_test['SOP'])

LOR_test = pd.DataFrame(x_test['LOR '])

CGPA_test = pd.DataFrame(x_test['CGPA'])

Research_test = pd.DataFrame(x_test['Research'])

### Reg: Serial_No

In [608]:
linReg_Serial_No = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(Serial_No_train, y_train)

In [609]:
linReg_Serial_No.coef_

array([[4.27833034e-05]])

In [610]:
linReg_Serial_No.intercept_

array([0.71789516])

In [611]:
R_sqaured = linReg_Serial_No.score(Serial_No_train, y_train)
R_sqaured

0.001157585362535074

### Reg: GRE_Score

In [557]:
linReg_GRE_Score = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(GRE_Score_train, y_train)

In [558]:
linReg_GRE_Score.coef_

array([[0.01012352]])

In [559]:
linReg_GRE_Score.intercept_

array([-2.48075999])

In [560]:
R_sqaured = linReg_GRE_Score.score(GRE_Score_train, y_train)
R_sqaured

0.6648144185270135

### Reg: TOEFL_Score

In [676]:
linReg_TOEFL_Score = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(TOEFL_Score_train, y_train)

In [677]:
linReg_TOEFL_Score.coef_

array([0.01876077])

In [678]:
linReg_TOEFL_Score.intercept_

-1.2890124882689267

In [679]:
R_sqaured = linReg_TOEFL_Score.score(TOEFL_Score_train, y_train)
R_sqaured

0.626977828226303

### Reg: University_Rating

In [565]:
linReg_University_Rating = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(University_Rating_train, y_train)

In [566]:
linReg_University_Rating.coef_

array([[0.09139658]])

In [567]:
linReg_University_Rating.intercept_

array([0.44218438])

In [568]:
R_sqaured = linReg_University_Rating.score(University_Rating_train, y_train)
R_sqaured

0.534834191581839

### Reg: SOP

In [569]:
linReg_SOP = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(SOP_train, y_train)

In [570]:
linReg_SOP.coef_

array([[0.09454311]])

In [571]:
linReg_SOP.intercept_

array([0.40373246])

In [572]:
R_sqaured = linReg_SOP.score(SOP_train, y_train)
R_sqaured

0.4597990858762536

### Reg: LOR

In [573]:
linReg_LOR = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(LOR_train, y_train)

In [574]:
linReg_LOR.coef_

array([[0.10832139]])

In [575]:
linReg_LOR.intercept_

array([0.35007017])

In [576]:
R_sqaured = linReg_LOR.score(LOR_train, y_train)
R_sqaured

0.4604611943302088

### Reg: CGPA

In [672]:
linReg_CGPA = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(CGPA_train, y_train)

In [673]:
linReg_CGPA.coef_

array([0.21024339])

In [674]:
linReg_CGPA.intercept_

-1.0844197441854437

In [675]:
R_sqaured = linReg_CGPA.score(CGPA_train, y_train)
R_sqaured

0.7818037402615292

### Reg: Research

In [581]:
linReg_Research = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(Research_train, y_train)

In [582]:
linReg_Research.coef_

array([[0.16429851]])

In [583]:
linReg_Research.intercept_

array([0.63475177])

In [584]:
R_sqaured = linReg_Research.score(Research_train, y_train)
R_sqaured

0.3200294958893064

## Question 3 - Cross Validation: SVM

### Serial_No

In [651]:
cross_val_Serial_No = svm.SVR(kernel='linear', C=1).fit(Serial_No_test, y_test)
cross_val_Serial_No.score(Serial_No_test, y_test)

-0.013292931497668413

### GRE_Score

In [664]:
cross_val_GRE_Score = svm.SVR(kernel='linear', C=1).fit(GRE_Score_test, y_test)
cross_val_GRE_Score.score(GRE_Score_test, y_test)

0.5557987662875494

### TOEFL_Score

In [665]:
cross_val_TOEFL_Score = svm.SVR(kernel='linear', C=1).fit(TOEFL_Score_test, y_test)
cross_val_TOEFL_Score.score(TOEFL_Score_test, y_test)

0.625368544672859

### University_Rating

In [667]:
cross_val_University_Rating = svm.SVR(kernel='linear', C=1).fit(University_Rating_test, y_test)
cross_val_University_Rating.score(University_Rating_test, y_test)

0.3794545371667612

### SOP

In [668]:
cross_val_SOP = svm.SVR(kernel='linear', C=1).fit(SOP_test, y_test)
cross_val_SOP.score(SOP, y_test)

0.4369833088806138

### LOR

In [669]:
cross_val_LOR = svm.SVR(kernel='linear', C=1).fit(LOR_test, y_test)
cross_val_LOR.score(LOR, y_test)

0.39548592566218094

### CGPA

In [670]:
cross_val_CGPA = svm.SVR(kernel='linear', C=1).fit(CGPA_test, y_test)
cross_val_CGPA.score(CGPA_test, y_test)

0.6309570163973492

### Research 

In [671]:
cross_val_Research = svm.SVR(kernel='linear', C=1).fit(Research_test, y_test)
cross_val_Research.score(Research_test, y_test)

0.24459822192636413

## Question 4 - Applying the best coefficient to the application data set

What exactly does this mean....?

In [683]:
test_data.columns

Index(['CGPA', 'Chance of Admit', 'GRE Score', 'LOR', 'Research', 'SOP',
       'Serial No.', 'TOEFL Score', 'University Rating'],
      dtype='object')

In [736]:
y_app = test_data[['CGPA']]

CGPA_app = test_data[['CGPA']]

#x_app = test_data[['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research']]

#y_app
#CGPA_app
#x_app

CGPA
0   8.38
1   8.79
2   8.60
3   9.09
4   8.80
5   8.89
6   9.64
7   9.22
8   9.20
9   9.10
10  9.01
11  9.04
12  7.70
13  7.89
14  8.00
15  8.15
16  8.33
17  8.55
18  8.71
19  9.08
20  9.27

In [759]:
linReg_test_data = LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=None).fit(CGPA_app, y_app)

In [760]:
linReg_test_data.coef_

array([[1.]])

In [761]:
linReg_test_data.intercept_

array([0.])

In [762]:
R_sqaured = linReg_LOR.score(CGPA_app, y_app)
R_sqaured
#WTF?

-225.6329053739533

In [767]:
y_predict = pd.DataFrame(linReg_test_data.predict(CGPA_app))
y_predict = y_predict.rename(columns={0:'CGPA_Predictions'})
y_predict

CGPA_Predictions
0               8.38
1               8.79
2               8.60
3               9.09
4               8.80
5               8.89
6               9.64
7               9.22
8               9.20
9               9.10
10              9.01
11              9.04
12              7.70
13              7.89
14              8.00
15              8.15
16              8.33
17              8.55
18              8.71
19              9.08
20              9.27

In [768]:
MSE = sklearn.metrics.mean_squared_error(y_app, y_predict, sample_weight=None, multioutput='uniform_average')
MSE

0.0

**Soo is this right? Even with a -22563.3% R-squared.....?**

## Question 5 - Write results to a JSON file

In [773]:
CGPA_Predictions = y_predict.to_json()

### Left over code I don't want to delete

In [166]:
def map_y(row):
    construction = row["construction"]
    
    construction_switch = {
        "Masonry": 1,
        "Wood": 2,
        "Reinforced Concrete": 3
    }
    
    county_switch = {
        "CLAY COUNTY": 10,
        "SUWANNEE COUNTY": 20,
    }
    
    return pd.Series([construction_switch[construction]])

y = y.apply(map_y, axis=1)

In [651]:
cross_val_Serial_No = svm.SVR(kernel='linear', C=1).fit(Serial_No_test, y_test)
cross_val_Serial_No.score(Serial_No_test, y_test)

-0.013292931497668413

In [688]:
kf = KFold(n_splits=5)
>>> for Serial_No_test, y_test in kf.split(X):
...     print("%s %s" % (Serial_No_test, y_test))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47] [0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47] [10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47] [20 21 22 23 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 39 40 41 42 43 44 45 46 47] [30 31 32 33 34 35 36 37 38]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38] [39 40 41 42 43 44 45 46 47]
